### PR TITLE
Fix for #21815 : Incorrect URL for openDS download in security devtest

### LINKED ISSUE #21815: Incorrect URL for openDS download in security devtest
The security devtests uses [http://java.net/downloads/opends/promoted-builds/2.2.1/OpenDS-2.2.1.zip](url) link to download OpenDS zip. This link is no longer active. This results in some of the tests which uses OpenDS getting skipped.

## Environment Details
* GlassFish Version (and build number): 5.0
* JDK version: 1.8.0.1_121
* OS: Linux

### PR DESCRIPTION
**Pull request by kokil12**
Fixes #21815 : The OpenDS-2.2.1.zip download location has been changed.

### CODE REVIEW

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]

File: main/appserver/tests/appserv-tests/devtests/security/run_test.sh [hunk 1]
```diff
@@ -43,15 +43,16 @@ test_run(){
 	rm -rf opends-image
 	mkdir opends-image
 	pushd opends-image
-
-	wget --no-check-certificate http://java.net/downloads/opends/promoted-builds/2.2.1/OpenDS-2.2.1.zip
-	unzip -q OpenDS-2.2.1.zip
+	
+	unzip -q /net/gf-hudson/scratch/java_re_node/OpenDS-2.2.1.zip
```
Comment (arindam-bandyopadhyay) [inline main/appserver/tests/appserv-tests/devtests/security/run_test.sh]: Please pass an environment variable with the location
